version: "3.7"
services:
  app:
    build:
      args:
        user: habtetsega
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: job
    container_name: job
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel
  db:
    image: mysql:8.0
    container_name: my_sql1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_PASSWORD: 
      MYSQL_USER: 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel
  nginx:
    image: nginx:alpine
    container_name: nigix-cont1
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
